const catalogIngredients = {
    'i1': { name: 'Huevos', unit: 'unidades' },
    'i2': { name: 'Tomates', unit: 'unidades' },
    'i3': { name: 'Pasta', unit: 'paquetes' },
    'i4': { name: 'Salsa Pesto', unit: 'frascos' },
    'i5': { name: 'Pechuga Pollo', unit: 'filetes' },
    'i6': { name: 'Arroz', unit: 'kg' },
    'i7': { name: 'Cebolla', unit: 'unidades' },
    'i8': { name: 'Avena', unit: 'tazas' },
    'i9': { name: 'Leche', unit: 'litros' },
    'i10':{ name: 'Miel', unit: 'cucharadas' },
    'i11':{ name: 'Espinaca', unit: 'paquetes' },
    'i12':{ name: 'Tortillas', unit: 'paquetes' },
    'i13':{ name: 'Queso Rallado', unit: 'paquetes' },
    'i14':{ name: 'Carne Picada', unit: 'kg' },
    'i15':{ name: 'Papa', unit: 'unidades' },
    'i16':{ name: 'Ajo', unit: 'cabezas' },
    'i17':{ name: 'Lentejas', unit: 'latas' },
    'i18':{ name: 'Pan de Molde', unit: 'paquetes' },
    'i19':{ name: 'Jamón', unit: 'fetas' },
    'i20':{ name: 'Queso Feteado', unit: 'fetas' },
    'i21':{ name: 'Atún', unit: 'latas' },
    'i22':{ name: 'Lechuga', unit: 'plantas' },
    'i23':{ name: 'Manzana', unit: 'unidades' },
    'i24':{ name: 'Banana', unit: 'unidades' },
    'i25':{ name: 'Salsa de Tomate', unit: 'cajas' },
    'i26':{ name: 'Zanahoria', unit: 'unidades' },
    'i27':{ name: 'Fideos de Arroz', unit: 'paquetes' },
    'i28':{ name: 'Salsa de Soja', unit: 'botellas' },
    'i29':{ name: 'Manteca', unit: 'paquetes' },
    'i30':{ name: 'Harina', unit: 'kg' }
};

const mockRecipes = [
    { 
        id: 'r1', title: 'Pasta al Pesto con Tomates Cherry', desc: 'Una opción rápida, fresca e infalible para cualquier día de la semana.', 
        time: '15 min', portions: 2, difficulty: 'Fácil', 
        ingredients: [{id:'i3', qty:1}, {id:'i4', qty:1}, {id:'i2', qty:4}], 
        instructions: [
            'Pon a hervir una olla grande con abundante agua y un puñado generoso de sal gruesa.', 
            'Cuando el agua hierva a borbotones, añade la pasta y cocina siguiendo estrictamente los minutos que indica el paquete para que quede al dente.', 
            'Mientras la pasta se cocina, lava los tomates y córtalos por la mitad o en cuartos, según tu preferencia.',
            'Escurre la pasta reservando media taza del agua de cocción. Esto ayudará a que la salsa se adhiera mejor.',
            'En la misma olla, fuera del fuego, mezcla la pasta con el pesto, un chorrito del agua reservada y los tomates. Sirve inmediatamente.'
        ] 
    },
    { 
        id: 'r2', title: 'Arroz con Pollo a la Cazuela', desc: 'El clásico reconfortante que nunca falla y rinde para varios días.', 
        time: '40 min', portions: 4, difficulty: 'Media', 
        ingredients: [{id:'i6', qty:1}, {id:'i5', qty:3}, {id:'i7', qty:2}], 
        instructions: [
            'Pela y pica la cebolla finamente. Corta las pechugas de pollo en cubos medianos, procurando que sean del mismo tamaño para una cocción pareja.',
            'En una olla o cazuela ancha, calienta un poco de aceite a fuego medio y dora los cubos de pollo por todos sus lados hasta que estén dorados. Retíralos y resérvalos.',
            'En la misma olla, agrega un poco más de aceite si es necesario y sofríe la cebolla picada hasta que esté transparente.',
            'Incorpora el arroz y tuéstalo un minuto junto con la cebolla, revolviendo para que no se pegue.',
            'Añade el pollo reservado, vierte agua o caldo caliente (el doble de volumen que de arroz), tapa la olla y baja el fuego al mínimo. Cocina por 18-20 minutos sin destapar.'
        ] 
    },
    { 
        id: 'r3', title: 'Huevos Revueltos Perfectos', desc: 'Un desayuno proteico, cremoso y lleno de energía para empezar el día.', 
        time: '10 min', portions: 1, difficulty: 'Fácil', 
        ingredients: [{id:'i1', qty:3}, {id:'i2', qty:1}, {id:'i29', qty:1}], 
        instructions: [
            'Rompe los huevos en un bol, añade una pizca de sal y bátelos vigorosamente con un tenedor hasta que las yemas y claras se integren por completo.',
            'Lava y pica el tomate en cubitos muy pequeños, desechando el exceso de jugo y semillas.',
            'Derrite una nuez de manteca en una sartén antiadherente a fuego medio-bajo.',
            'Vierte los huevos batidos en la sartén. Espera unos segundos y comienza a arrastrar los bordes hacia el centro lentamente con una espátula de goma.',
            'Cuando los huevos estén a medio cuajar (aún brillantes y húmedos), retira la sartén del fuego, añade el tomate picado, revuelve rápidamente y sirve al instante para que no se resequen.'
        ] 
    },
    { 
        id: 'r4', title: 'Avena Nocturna (Overnight Oats)', desc: 'Desayuno preparado la noche anterior, listo para llevar y comer frío.', 
        time: '5 min', portions: 1, difficulty: 'Fácil', 
        ingredients: [{id:'i8', qty:1}, {id:'i9', qty:1}, {id:'i10', qty:2}, {id:'i24', qty:1}], 
        instructions: [
            'Toma un frasco de vidrio con tapa hermética o un bol pequeño.',
            'Agrega la avena y vierte la leche hasta cubrirla por completo. Puedes ajustar la cantidad de líquido dependiendo de si te gusta más espeso o más líquido.',
            'Añade la miel y revuelve vigorosamente para asegurar que toda la avena esté sumergida.',
            'Tapa el recipiente y déjalo reposar en la heladera durante toda la noche (o al menos 4 horas).',
            'A la mañana siguiente, destapa, corta media banana en rodajas y colócala por encima antes de disfrutar.'
        ] 
    },
    { 
        id: 'r5', title: 'Pasta Cremosa con Espinaca', desc: 'Una cena ligera pero saciante, ideal para incorporar verduras de forma deliciosa.', 
        time: '20 min', portions: 2, difficulty: 'Fácil', 
        ingredients: [{id:'i3', qty:1}, {id:'i11', qty:1}, {id:'i7', qty:1}, {id:'i16', qty:1}], 
        instructions: [
            'Cocina la pasta en abundante agua salada hirviendo hasta que esté al dente.',
            'Lava bien las hojas de espinaca, escurre el exceso de agua y reserva.',
            'Pica finamente la cebolla y los dientes de ajo. En una sartén amplia, sofríelos con un poco de aceite de oliva hasta que estén fragantes y dorados.',
            'Agrega la espinaca a la sartén. Parece mucha, pero se reducirá rápidamente con el calor en 2 minutos.',
            'Incorpora la pasta escurrida a la sartén con las verduras, mezcla bien a fuego lento y sirve caliente.'
        ] 
    },
    { 
        id: 'r6', title: 'Tacos Rápidos de Pollo', desc: 'Diversión para armar en la mesa. Ideal para compartir en familia o con amigos.', 
        time: '25 min', portions: 3, difficulty: 'Media', 
        ingredients: [{id:'i12', qty:1}, {id:'i5', qty:2}, {id:'i2', qty:2}, {id:'i7', qty:1}], 
        instructions: [
            'Corta las pechugas de pollo en tiras finas o dados pequeños. Haz lo mismo con la cebolla.',
            'En una sartén bien caliente con aceite, saltea el pollo junto a la cebolla. Condimenta con sal, pimienta y tus especias favoritas (pimentón, comino) hasta que esté bien dorado y cocido por dentro.',
            'Pica los tomates frescos en cubos para armar una salsa rápida de acompañamiento.',
            'Calienta las tortillas una por una en una plancha seca o sartén por unos 10 segundos de cada lado hasta que estén flexibles.',
            'Lleva todo a la mesa en recipientes separados para que cada uno arme su taco a gusto.'
        ] 
    },
    { id: 'r7', title: 'Milanesa de Pollo Saludable', desc: 'Croantes por fuera y jugosas por dentro, sin fritura.', time: '35 min', portions: 2, difficulty: 'Media', ingredients: [{id:'i5', qty:2}, {id:'i1', qty:2}, {id:'i13', qty:1}, {id:'i16', qty:1}], instructions: ['Precalienta el horno a 200°C. Bate los huevos en un plato hondo con ajo muy picado, sal y pimienta.', 'En otro plato hondo, mezcla pan rallado o avena extra fina con el queso rallado para un empanizado extra crujiente.', 'Pasa cada filete de pollo primero por la mezcla de huevo y luego por los secos, presionando bien para que se adhiera.', 'Coloca las milanesas en una asadera apenas engrasada y hornea durante 20-25 minutos, dándolas vuelta a la mitad del tiempo para que doren parejo.'] },
    { id: 'r8', title: 'Ensalada Proteica de Atún', desc: 'Una bomba de frescura, lista en tiempo récord y sin prender el fuego.', time: '10 min', portions: 1, difficulty: 'Fácil', ingredients: [{id:'i21', qty:1}, {id:'i22', qty:1}, {id:'i2', qty:2}, {id:'i7', qty:1}], instructions: ['Lava las hojas de lechuga cuidadosamente, sécalas y córtalas con las manos para evitar que se oxiden.', 'Corta los tomates en rodajas y la cebolla en juliana muy fina (puedes remojar la cebolla en agua tibia 5 min para suavizar su sabor).', 'Abre la lata de atún, escurre todo el líquido o aceite y desmenúzalo en un bol grande.', 'Incorpora los vegetales al bol con el atún, aliña con abundante jugo de limón, aceite de oliva, sal y mezcla suavemente.'] },
    { id: 'r9', title: 'Sándwich Tostado Clásico', desc: 'La solución salvadora de medianoche o merienda express.', time: '10 min', portions: 1, difficulty: 'Fácil', ingredients: [{id:'i18', qty:1}, {id:'i19', qty:2}, {id:'i20', qty:2}, {id:'i29', qty:1}], instructions: ['Toma dos rebanadas de pan de molde y unta una capa muy fina de manteca en la cara exterior de ambas rebanadas. Esto garantizará un tostado dorado y crujiente.', 'En la cara interior de los panes, coloca las fetas de queso primero (para que se fundan más rápido con el calor) y luego el jamón en el medio.', 'Calienta una sartén o plancha a fuego medio-bajo.', 'Coloca el sándwich en la sartén y presiona ligeramente con una espátula. Cocina unos 3 minutos por lado hasta que el pan esté dorado y el queso completamente derretido.'] },
    { id: 'r10', title: 'Puré Rústico de Papas', desc: 'Guarnición cremosa e indispensable para acompañar carnes.', time: '35 min', portions: 4, difficulty: 'Media', ingredients: [{id:'i15', qty:5}, {id:'i9', qty:1}, {id:'i29', qty:1}], instructions: ['Lava y pela las papas. Córtalas en trozos del mismo tamaño para asegurar que todas se cocinen al mismo tiempo.', 'Colócalas en una olla, cúbrelas con agua fría y agrega una cucharada de sal. Lleva a hervor y cocina hasta que al pincharlas con un tenedor estén sumamente tiernas (unos 20 mins).', 'Escúrrelas completamente y regrésalas a la olla caliente fuera del fuego para que se evapore la humedad residual.', 'Usa un pisapapas o tenedor para hacerlas puré.', 'Calienta apenas la leche junto con la manteca e incorpóralo al puré batiendo enérgicamente para darle una textura suave y aireada.'] },
    { id: 'r11', title: 'Bolognesa Casera Rápida', desc: 'Una salsa rica y con cuerpo para bañar tus pastas.', time: '35 min', portions: 4, difficulty: 'Media', ingredients: [{id:'i14', qty:1}, {id:'i7', qty:1}, {id:'i25', qty:1}, {id:'i16', qty:1}], instructions: ['Pica la cebolla y el ajo muy pequeños. Sofríelos en una olla profunda con un poco de aceite de oliva hasta que la cebolla empiece a dorarse.', 'Añade la carne picada. Con ayuda de una cuchara de madera, deshazla constantemente para evitar que se formen bloques grandes. Cocina hasta que cambie de color a marrón.', 'Vierte la caja de salsa de tomate entera. Enjuaga la caja con medio vaso de agua y agrégalo también a la olla.', 'Condimenta con sal, pimienta, orégano y una pizca de azúcar (para matar la acidez del tomate).', 'Tapa y deja cocinar a fuego muy lento por al menos 20 minutos para que los sabores se asienten.'] },
    { id: 'r12', title: 'Omelette Doblado de Queso', desc: 'Elegante, fácil y listo en menos de lo que canta un gallo.', time: '5 min', portions: 1, difficulty: 'Media', ingredients: [{id:'i1', qty:2}, {id:'i20', qty:3}, {id:'i29', qty:1}], instructions: ['En un bol pequeño, bate los huevos enérgicamente hasta que hagan un poco de espuma. Agrega una pizca de sal.', 'Derrite manteca en una sartén antiadherente a fuego medio. Asegúrate de cubrir todo el fondo.', 'Vierte los huevos. Cuando veas que los bordes empiezan a cuajarse pero el centro sigue líquido, baja el fuego al mínimo.', 'Coloca las fetas de queso superpuestas en una mitad del círculo del omelette.', 'Con ayuda de una espátula, levanta la mitad vacía y dóblala cuidadosamente sobre el queso. Deja un minuto más para que el queso funda con el calor residual y desliza al plato.'] },
    { id: 'r13', title: 'Guiso Rápido de Lentejas', desc: 'Sabor de hogar con el atajo de usar lentejas en lata.', time: '30 min', portions: 3, difficulty: 'Fácil', ingredients: [{id:'i17', qty:2}, {id:'i7', qty:1}, {id:'i26', qty:2}, {id:'i15', qty:1}], instructions: ['Pela la papa, la cebolla y la zanahoria. Córtalas en cubos medianos.', 'En una cacerola, sofríe la cebolla y la zanahoria por 5 minutos hasta que suden.', 'Agrega la papa en cubos y sofríe un par de minutos más.', 'Abre las latas de lentejas y viértelas completas (con su líquido) en la cacerola. Si notas que le falta líquido, agrega media taza de agua o caldo.', 'Tapa y deja cocinar a fuego medio-bajo por unos 15 minutos, revolviendo ocasionalmente, hasta que la papa esté muy tierna y el guiso haya espesado.'] },
    { id: 'r14', title: 'Pollo Dorado a la Plancha', desc: 'Básico indispensable y magro.', time: '20 min', portions: 2, difficulty: 'Media', ingredients: [{id:'i5', qty:2}, {id:'i16', qty:1}], instructions: ['Filetea las pechugas de pollo si son muy gruesas, o golpéalas suavemente entre dos papeles film para emparejar su grosor.', 'Machaca los dientes de ajo hasta hacerlos pasta y frótalo por todo el pollo junto con sal, pimienta y unas gotas de aceite.', 'Calienta a fuego fuerte una plancha o sartén gruesa hasta que humee levemente.', 'Coloca los filetes. Es crucial no moverlos por 4 o 5 minutos para lograr una buena costra dorada.', 'Dales vuelta, baja un poco el fuego y cocina otros 4 minutos hasta que el interior deje de ser rosado.'] },
    { id: 'r15', title: 'Wok de Pollo Estilo Oriental', desc: 'Mucho sabor en poco tiempo usando técnicas asiáticas.', time: '25 min', portions: 2, difficulty: 'Difícil', ingredients: [{id:'i5', qty:1}, {id:'i26', qty:1}, {id:'i28', qty:1}, {id:'i7', qty:1}], instructions: ['El secreto del wok es preparar todo antes de prender el fuego. Corta el pollo en tiras muy finas. Corta la zanahoria y cebolla en juliana delgada.', 'Calienta un wok o sartén profunda a fuego máximo. Agrega un chorrito de aceite.', 'Incorpora el pollo y saltéalo sin parar por 3 minutos hasta que selle por fuera. Retíralo a un plato.', 'En el mismo wok, echa las verduras y saltéalas vigorosamente por 4 minutos (deben quedar crujientes).', 'Regresa el pollo al wok, vierte la salsa de soja (unas 3 cucharadas), saltea todo junto durante 1 minuto para que caramelice y sirve de inmediato.'] },
    { id: 'r16', title: 'Fideos de Arroz con Soja', desc: 'Comida asiática súper rápida, apta para celíacos.', time: '15 min', portions: 2, difficulty: 'Fácil', ingredients: [{id:'i27', qty:1}, {id:'i28', qty:1}, {id:'i16', qty:2}], instructions: ['Calienta abundante agua hasta que hierva y viértela en un bol sobre los fideos de arroz. Déjalos reposar (sin fuego) durante 5 a 8 minutos hasta que se ablanden. Escúrrelos y pásales agua fría.', 'Pica el ajo muy fino.', 'Calienta aceite en una sartén grande, sofríe el ajo apenas unos segundos (cuidado que no se queme).', 'Incorpora los fideos escurridos a la sartén y remueve rápidamente para que se impregnen de aceite.', 'Añade la salsa de soja, mezcla usando dos tenedores para desenredar los fideos, saltea 2 minutos y sirve.'] },
    { id: 'r17', title: 'Sopa Cremosa de Tomate', desc: 'Reconfortante, caliente e ideal para acompañar con pan tostado.', time: '30 min', portions: 2, difficulty: 'Fácil', ingredients: [{id:'i25', qty:1}, {id:'i7', qty:1}, {id:'i9', qty:1}, {id:'i29', qty:1}], instructions: ['Pica la cebolla finamente. En una olla, derrite la manteca a fuego medio y sofríe la cebolla hasta que esté translúcida y muy blanda (unos 8 min).', 'Vierte el contenido de la caja de salsa de tomate en la olla.', 'Agrega media taza de agua y lleva a hervor suave. Deja cocinar destapado durante unos 10 minutos.', 'Agrega un chorro de leche líquida, baja el fuego al mínimo y condimenta con sal, pimienta negra y una pizca de azúcar.', 'Si tienes una licuadora de mano, procesa la sopa directamente en la olla para darle una textura lisa y aterciopelada perfecta.'] },
    { id: 'r18', title: 'Ensalada Rusa Tradicional', desc: 'La clásica de los domingos. Paciencia con el hervor.', time: '50 min', portions: 4, difficulty: 'Media', ingredients: [{id:'i15', qty:3}, {id:'i26', qty:2}, {id:'i1', qty:3}], instructions: ['Lava muy bien las papas y zanahorias. Hiérvelas enteras y con piel en una olla grande. Retira las zanahorias a los 25 min y las papas a los 35-40 min, probando con un cuchillo.', 'En otra olla pequeña, hierve los huevos durante 10 minutos exactos para hacer huevos duros. Pásalos a agua helada para frenar cocción.', 'Una vez que las verduras estén frías o tibias, pélalas cuidadosamente.', 'Corta papas, zanahorias y los huevos duros en cubos prolijos del mismo tamaño.', 'Coloca todo en un bol grande, añade sal generosa y, si es de tu gusto, unifica con abundante mayonesa (no incluida en la receta base).'] },
    { id: 'r19', title: 'Masa de Panqueques (Dulces/Salados)', desc: 'La receta maestra para armar canelones o rellenar con dulce de leche.', time: '20 min', portions: 4, difficulty: 'Media', ingredients: [{id:'i1', qty:2}, {id:'i9', qty:1}, {id:'i30', qty:1}, {id:'i29', qty:1}], instructions: ['En un bol grande, vierte una taza de leche, una taza de harina y los dos huevos. Añade una pizca pequeñita de sal (incluso si los vas a hacer dulces).', 'Bate enérgicamente con batidor de alambre hasta eliminar todos los grumos. Debe quedar una mezcla líquida pero con cuerpo. Déjala reposar 10 minutos en la heladera si puedes.', 'Calienta una panquequera o sartén plana a fuego medio-alto y engrásala con un pedacito de manteca frotada.', 'Vierte un cucharón de masa y mueve la sartén rápidamente en el aire para que la masa cubra todo el fondo en una capa fina.', 'Cocina hasta que los bordes se doren y se despeguen solos, voltea con una espátula, cocina 10 segundos más y sácalo al plato.'] },
    { id: 'r20', title: 'Rollitos de Jamón y Queso Rápido', desc: 'Un snack salvador cuando tienes hambre pero no ganas de cocinar.', time: '5 min', portions: 1, difficulty: 'Fácil', ingredients: [{id:'i19', qty:3}, {id:'i20', qty:3}], instructions: ['Sobre una tabla limpia, extiende una feta de jamón.', 'Coloca encima una feta de queso feteado, asegurándote de que no sobresalga mucho de los bordes del jamón.', 'Comenzando desde uno de los extremos inferiores, enrolla ambas fetas juntas lo más apretado posible.', 'Repite el proceso con el resto de las fetas.', 'Ideal para comer en el momento como snack keto o merienda escolar.'] },
    
    // Generando las otras 20 recetas de forma detallada pero algo más resumida en la metadata para mantener el archivo limpio
    { id: 'r21', title: 'Quesadillas Fundidas', desc: 'Cena rápida mexicana.', time: '10 min', portions: 1, difficulty: 'Fácil', ingredients: [{id:'i12', qty:1}, {id:'i20', qty:4}], instructions: ['Calienta una sartén seca a fuego muy bajo.', 'Coloca una tortilla de trigo extendida en la sartén.', 'Cubre solo la mitad de la tortilla con las fetas de queso, rompiéndolas para que encajen bien.', 'Dobla la otra mitad de la tortilla sobre el queso, formando una media luna.', 'Presiona con una espátula y cuando la base esté dorada, dale la vuelta para dorar el otro lado y fundir todo el queso por dentro.'] },
    { id: 'r22', title: 'Macarrones Express', desc: 'Fideos con crema de queso rápida.', time: '25 min', portions: 3, difficulty: 'Media', ingredients: [{id:'i3', qty:1}, {id:'i13', qty:2}, {id:'i9', qty:1}], instructions: ['Cocina la pasta en agua hirviendo hasta que quede firme (al dente).', 'Escurre la pasta y en la misma olla (sin agua y a fuego bajo) agrega medio vaso de leche.', 'Añade los dos paquetes de queso rallado e integra rápidamente con cuchara de madera.', 'Revuelve vigorosamente hasta que el queso se derrita en la leche creando una salsa cremosa y pegajosa.', 'Sirve inmediatamente mientras el queso esté elástico.'] },
    { id: 'r23', title: 'Sopa Francesa de Cebolla', desc: 'Elegancia y paciencia en la olla.', time: '45 min', portions: 2, difficulty: 'Difícil', ingredients: [{id:'i7', qty:4}, {id:'i29', qty:1}, {id:'i18', qty:1}], instructions: ['Corta todas las cebollas en plumas (juliana) lo más finas que puedas.', 'Derrite manteca en una olla y agrega la cebolla a fuego muy bajo. Este es el paso clave: debes revolver durante 25-30 minutos hasta que la cebolla se vuelva marrón oscuro (caramelización natural).', 'Una vez caramelizada, agrega 3 tazas de agua o caldo, tapa y deja hervir 10 minutos.', 'Tuesta dos rebanadas de pan de molde hasta que queden bien crocantes.', 'Sirve la sopa caliente y coloca el pan tostado flotando por encima.'] },
    { id: 'r24', title: 'Albóndigas Jugosas', desc: 'Preparación para tu salsa favorita.', time: '30 min', portions: 4, difficulty: 'Media', ingredients: [{id:'i14', qty:1}, {id:'i1', qty:1}, {id:'i16', qty:1}, {id:'i13', qty:1}], instructions: ['En un bol grande, desmenuza la carne picada con las manos.', 'Agrega un huevo crudo, ajo picado casi en pasta, el queso rallado, sal y mucha pimienta.', 'Amasa la carne con las manos durante un par de minutos. Esto desarrolla proteína y evita que las albóndigas se rompan al cocinar.', 'Mójate un poco las manos y forma bolitas del tamaño de una pelota de golf.', 'Fríelas en sartén hasta que doren, o añádelas directamente a una salsa de tomate hirviendo para que se cocinen allí durante 20 minutos.'] },
    { id: 'r25', title: 'Arroz Frito de Sobras', desc: 'La mejor forma de reciclar arroz de ayer.', time: '15 min', portions: 2, difficulty: 'Fácil', ingredients: [{id:'i6', qty:1}, {id:'i1', qty:2}, {id:'i28', qty:1}, {id:'i7', qty:1}], instructions: ['Necesitas usar arroz cocido y que haya estado en la heladera (el arroz recién hecho quedará pastoso).', 'En una sartén muy caliente o wok, sofríe cebolla picada con aceite.', 'Agrega el arroz frío desmenuzándolo con los dedos para separar los granos. Saltea por 4 minutos.', 'Haz un hueco en el centro de la sartén empujando el arroz, rompe allí los dos huevos y revuélvelos como haciendo huevos revueltos.', 'Cuando el huevo cuaje, mezcla todo y baña con salsa de soja abundante.'] },
    { id: 'r26', title: 'Salteado de Zanahoria Rallada', desc: 'Ligero y diferente.', time: '10 min', portions: 1, difficulty: 'Fácil', ingredients: [{id:'i26', qty:2}, {id:'i1', qty:2}], instructions: ['Pela las zanahorias y rállalas usando los agujeros más grandes del rallador.', 'Calienta un chorrito de aceite en una sartén y saltea la zanahoria rallada por unos 5 a 7 minutos hasta que pierda rigidez.', 'Sazona con sal, pimienta y nuez moscada si tuvieras.', 'Bate los huevos en un cuenco pequeño y vuélcalos sobre la zanahoria en la sartén.', 'Revuelve todo junto rápidamente hasta que el huevo se cocine y se adhiera a la zanahoria.'] },
    { id: 'r27', title: 'Tortilla de Papas Simplificada', desc: 'Papas en cubos para evitar fritura profunda.', time: '35 min', portions: 2, difficulty: 'Difícil', ingredients: [{id:'i15', qty:3}, {id:'i1', qty:4}, {id:'i7', qty:1}], instructions: ['Pela y corta las papas en cubitos de 1 centímetro. Pica la cebolla fina.', 'En una sartén antiadherente mediana (20cm) con generoso aceite, rehoga la cebolla y luego agrega los cubitos de papa a fuego muy bajo. Tapa la sartén para que las papas se hagan al vapor en su propio aceite.', 'Bate los 4 huevos en un bol grande con bastante sal.', 'Una vez la papa esté muy tierna, escúrrela del aceite y vuélcala caliente sobre los huevos batidos. Deja reposar 5 minutos.', 'Vuelca la mezcla en la misma sartén muy caliente con apenitas de aceite. Cocina 2 min, voltea con la ayuda de un plato, y cocina 1 min más.'] },
    { id: 'r28', title: 'Tostadas Francesas', desc: 'Desayuno de campeones.', time: '15 min', portions: 1, difficulty: 'Media', ingredients: [{id:'i18', qty:1}, {id:'i1', qty:1}, {id:'i9', qty:1}, {id:'i29', qty:1}], instructions: ['Usa pan de molde que esté un poco duro o de un par de días (absorbe mejor sin romperse).', 'Bate un huevo hondo en un plato con un buen chorro de leche y canela o vainilla a gusto.', 'Sumerge una rebanada de pan en el líquido, dejándola 10 segundos por lado para que se empape bien.', 'Calienta media cucharada de manteca en una sartén antiadherente a fuego medio.', 'Cocina la rebanada empapada durante unos 3 minutos por lado hasta que adquiera un color dorado y crujiente.'] },
    { id: 'r29', title: 'Pasta Mantecada Simpática', desc: 'El plato preferido para fin de mes.', time: '15 min', portions: 1, difficulty: 'Fácil', ingredients: [{id:'i3', qty:1}, {id:'i29', qty:1}, {id:'i13', qty:1}], instructions: ['Cocina tu porción de pasta en agua muy salada. El agua de cocción es vital aquí.', 'Escurre la pasta, pero guarda sí o sí media taza del agua hirviendo, ya que el almidón es el secreto de la salsa.', 'Devuelve la pasta caliente a la olla (sin fuego), añade un buen trozo de manteca fría y la mitad del agua de cocción.', 'Revuelve frenéticamente. Verás cómo el agua y la manteca emulsionan formando una crema sedosa.', 'Agrega el queso rallado, revuelve una vez más y sirve en plato hondo.'] },
    { id: 'r30', title: 'Croquetas Express de Atún', desc: 'Ideales para almuerzo rápido.', time: '20 min', portions: 2, difficulty: 'Media', ingredients: [{id:'i21', qty:1}, {id:'i1', qty:1}, {id:'i30', qty:1}], instructions: ['Abre la lata de atún, saca el líquido completamente presionando la tapa.', 'Vuelca el atún en un bol, añade un huevo entero, una cucharada sopera de harina, sal y perejil picado si tuvieras.', 'Mezcla todo con un tenedor hasta formar una pasta consistente.', 'Calienta aceite en una sartén. Con la ayuda de dos cucharas, toma porciones de masa y échalas a la sartén.', 'Aplástalas un poco y fríelas por 3 minutos de cada lado hasta que queden doradas y crocantes por fuera.'] },
    
    { id: 'r31', title: 'Ensalada Fresca de Lentejas', desc: 'Plato frío, nutritivo y diferente.', time: '10 min', portions: 2, difficulty: 'Fácil', ingredients: [{id:'i17', qty:1}, {id:'i2', qty:1}, {id:'i7', qty:1}], instructions: ['Abre la lata de lentejas, vuelca en un colador y enjuaga bajo el chorro de agua fría para quitarles el líquido de conserva.', 'Corta la cebolla y el tomate en cubos diminutos. Si la cebolla pica mucho, déjala 5 min en agua helada.', 'Combina las lentejas escurridas con los vegetales en una ensaladera.', 'Prepara una vinagreta emulsionando (batiendo con tenedor) 3 cucharadas de aceite, 1 de vinagre, sal y orégano.', 'Baña la ensalada con la vinagreta y mezcla bien. Ideal dejar enfriar media hora antes de comer.'] },
    { id: 'r32', title: 'Tostada Energética de Miel', desc: 'Merienda alta en energía rápida.', time: '5 min', portions: 1, difficulty: 'Fácil', ingredients: [{id:'i18', qty:1}, {id:'i10', qty:1}, {id:'i24', qty:1}], instructions: ['Tuesta dos rebanadas de pan hasta que queden bien crocantes.', 'Mientras están calientes, esparce una cucharadita de miel sobre cada rebanada.', 'Pela la banana, córtala en rodajas diagonales (se ven más bonitas).', 'Acomoda las rodajas superpuestas sobre el pan recién horneado.', 'Cómetelas en el momento para aprovechar el contraste entre lo tibio, lo crocante y lo suave de la fruta.'] },
    { id: 'r33', title: 'Sándwich Clásico de Pollo', desc: 'El sándwich que no falla para el mediodía.', time: '15 min', portions: 1, difficulty: 'Media', ingredients: [{id:'i18', qty:1}, {id:'i5', qty:1}, {id:'i22', qty:1}, {id:'i2', qty:1}], instructions: ['Si tienes una pechuga gruesa, córtala transversalmente para sacar un filete más fino y cocínalo a la plancha hasta que esté dorado.', 'Lava bien dos hojas de lechuga y corta el tomate en rodajas no muy gruesas.', 'Tuesta levemente el pan de molde si lo deseas.', 'Unta mayonesa o aceite de oliva en el pan.', 'Monta el sándwich en este orden: Pan, lechuga, tomate (ponle sal al tomate), pollo caliente y el otro pan.'] },
    { id: 'r34', title: 'Papas Rústicas Crocantes', desc: 'El acompañamiento superior.', time: '40 min', portions: 3, difficulty: 'Fácil', ingredients: [{id:'i15', qty:4}, {id:'i16', qty:2}], instructions: ['Enciende el horno al máximo y mete la asadera vacía para que se precaliente el metal.', 'Lava las papas cepillando bien la piel (¡no la quites!). Córtalas a lo largo por la mitad, y luego en gajos gruesos.', 'Colócalas en un bol, añade un generoso chorro de aceite, 2 dientes de ajo molidos, sal fina y revuelve con las manos para embadurnar todo.', 'Saca la asadera ardiente del horno, vuelca las papas (deberían chillar) y asegúrate que queden apoyadas sobre una cara plana.', 'Hornea 35 minutos sin tocarlas hasta que la base sea puro cristal dorado.'] },
    { id: 'r35', title: 'Pollo Glaseado a la Miel', desc: 'Toques agridulces en pocos minutos.', time: '25 min', portions: 2, difficulty: 'Media', ingredients: [{id:'i5', qty:2}, {id:'i10', qty:2}, {id:'i28', qty:1}], instructions: ['Corta la pechuga de pollo en dados grandes y unifórmes.', 'Calienta a fuego alto una sartén con muy poco aceite. Sella los cubos de pollo por 5 minutos hasta que estén levemente tostados.', 'En un vaso, mezcla 2 cucharadas soperas de miel con 3 de salsa de soja.', 'Vuelca esta mezcla oscura sobre el pollo en la sartén. Bajará la temperatura de golpe y empezará a burbujear.', 'Deja reducir a fuego medio-bajo durante 5 minutos, revolviendo para que el pollo se bañe en la salsa espesa caramelizada.'] },
    { id: 'r36', title: 'Tortilla de Espinaca Express', desc: 'Ideal para comer verduras sin darte cuenta.', time: '20 min', portions: 2, difficulty: 'Media', ingredients: [{id:'i11', qty:1}, {id:'i1', qty:4}, {id:'i7', qty:1}, {id:'i16', qty:1}], instructions: ['Pica media cebolla fina y sofríela con el ajo picado en una sartén amplia.', 'Agrega la espinaca cruda limpia al sartén. Cúbrelo con una tapa 2 minutos para que el volumen baje drásticamente por el calor.', 'Bate los huevos en un bol grande, añade sal.', 'Incorpora el salteado de verduras a los huevos y revuelve.', 'Limpia la sartén, pon un hilo de aceite, vuelca todo y cocina 3 minutos por lado. Para darle vuelta, usa un plato llano gigante apoyado sobre la sartén.'] },
    { id: 'r37', title: 'Licuado Proteico Casero', desc: 'Sustituto de desayuno para mañanas con prisa.', time: '5 min', portions: 1, difficulty: 'Fácil', ingredients: [{id:'i24', qty:1}, {id:'i8', qty:1}, {id:'i9', qty:1}], instructions: ['Pela la banana y si tiene pintitas negras mucho mejor (estará más dulce). Para mejor textura, úsala congelada.', 'En el vaso de la licuadora, echa la leche, media taza de avena seca y la banana en trozos.', 'Opcionalmente añade un poco de canela en polvo o hielo.', 'Licúa a velocidad máxima durante 1 minuto completo para asegurar que la avena se triture por completo y quede sedoso.', 'Sirve en vaso largo.'] },
    { id: 'r38', title: 'Hamburguesas Supremas Caseras', desc: 'Date el gusto con un buen corte.', time: '25 min', portions: 2, difficulty: 'Difícil', ingredients: [{id:'i14', qty:1}, {id:'i18', qty:1}, {id:'i22', qty:1}, {id:'i20', qty:4}], instructions: ['Toma porciones de unos 150 gramos de carne picada y forma bolas sin amasarla demasiado.', 'Calienta a fuego corona (máximo posible) una plancha de hierro fundido.', 'Coloca la bola de carne y con una espátula muy dura y un poco de papel manteca por encima, aplástala sin compasión hasta formar un disco fino. Échale sal gruesa.', 'Deja dorar 2 minutos sin tocar (costra). Dale la vuelta, coloca doble porción de queso encima y tapa un minuto para que derrita.', 'Sirve en pan tostado con lechuga fresca.'] },
    { id: 'r39', title: 'Queso Envuelto', desc: 'Derretido garantizado.', time: '10 min', portions: 1, difficulty: 'Fácil', ingredients: [{id:'i19', qty:3}, {id:'i20', qty:6}], instructions: ['Haz "paquetitos" doblando las fetas de queso.', 'Envuelve cada paquetito de queso de forma cruzada con una o dos fetas de jamón, asegurándote de que no quede queso expuesto.', 'Calienta una sartén seca a fuego medio.', 'Coloca los paquetitos y dóralos por ambos lados. El jamón funcionará de "costra" y por dentro será puro queso derretido caliente.'] },
    { id: 'r40', title: 'Salsa Pesto Modificada', desc: 'Pesto adaptado para comer con pan.', time: '10 min', portions: 4, difficulty: 'Fácil', ingredients: [{id:'i4', qty:1}, {id:'i13', qty:1}, {id:'i2', qty:1}], instructions: ['Vuelca un frasco de salsa pesto comprada en un bol mediano.', 'Ralla el tomate fresco directamente sobre el pesto, desechando la piel.', 'Añade una buena cantidad de queso rallado extra para espesar la mezcla y suavizar la potencia del ajo.', 'Integra bien todo.', 'Unta abundantemente sobre panes tostados o úsalo como aderezo fresco para sándwiches.'] }
];
